export const c_record_fields = [
  {header: 'Record Type', field_name: 'record_type', start:1, size:1, default: 'C', required: true, description: ''},
  {header: 'SSN', field_name: 'ssn', start:2, size:9, default: '', required: true, description: ''},
  {header: 'First Name', field_name: 'first_name', start:11, size:20, default: '', required: true, description: ''},
  {header: 'Middle Name', field_name: 'middle_name', start:31, size:20, default: '', required: false, description: ''},
  {header: 'Last Name', field_name: 'last_name', start:51, size:35, default: '', required: true, description: ''},
  {header: 'Name Suffix', field_name: 'name_suffix', start:86, size:5, default: '', required: false, description: ''},
  {header: 'Address Line 1', field_name: 'address_line_1', start:91, size:35, default: '', required: true, description: ''},
  {header: 'Address Line 2', field_name: 'address_line_2', start:126, size:35, default: '', required: false, description: ''},
  {header: 'City', field_name: 'city', start:161, size:20, default: '', required: true, description: ''},
  {header: 'State', field_name: 'state', start:181, size:3, default: '', required: true, description: ''},
  {header: 'Zip/Postal Code', field_name: 'zip-postal_code', start:184, size:10, default: '', required: true, description: ''},
  {header: 'Country', field_name: 'country', start:194, size:2, default: '', required: true, description: ''},
  {header: 'Home Phone', field_name: 'home_phone', start:196, size:10, default: '', required: false, description: ''},
  {header: 'Work Phone', field_name: 'work_phone', start:206, size:10, default: '', required: false, description: ''},
  {header: 'Work Phone Ext', field_name: 'work_phone_ext', start:216, size:5, default: '', required: false, description: ''},
  {header: 'Fed Tax Exmpts', field_name: 'fed_tax_exmpts', start:221, size:2, default: '', required: false, description: ''},
  {header: 'PA Exclusion Amt', field_name: 'pa_exclusion_amt', start:223, size:13, default: '', required: false, description: ''},
  {header: 'Email Address', field_name: 'email_address', start:236, size:40, default: '', required: true, description: ''},
  {header: 'Hire Date', field_name: 'hire_date', start:276, size:8, default: '', required: true, description: ''},
  {header: 'Birth Date', field_name: 'birth_date', start:284, size:8, default: '', required: true, description: ''},
  {header: 'Status Date', field_name: 'status_date', start:292, size:8, default: '', required: true, description: ''},
  {header: 'Status Code', field_name: 'status_code', start:300, size:1, default: '', required: true, description: ''},
  {header: 'QNEC', field_name: 'qnec', start:301, size:13, default: '', required: false, description: ''},
  {header: 'Cost Center Code', field_name: 'cost_center_code', start:314, size:10, default: '', required: true, description: ''},
  {header: 'Enrollment ID', field_name: 'enrollment_id', start:324, size:10, default: '', required: true, description: ''},
  {header: 'Employer Org ID', field_name: 'employer_org_id', start:334, size:6, default: '', required: true, description: ''},
  {header: 'Gender', field_name: 'gender', start:340, size:1, default: '', required: true, description: ''},
  {header: 'Marital Status', field_name: 'marital_status', start:341, size:1, default: '', required: true, description: ''},
  {header: 'EE Guide', field_name: 'ee_guide', start:342, size:1, default: '', required: true, description: ''},
  {header: 'Fed Wages YTD', field_name: 'fed_wages_ytd', start:343, size:13, default: '', required: true, description: ''},
  {header: 'Deferred to Other TSA', field_name: 'deferred_to_other_tsa', start:356, size:13, default: '', required: false, description: ''},
  {header: 'Pre-Tax', field_name: 'pre-tax', start:369, size:13, default: '', required: false, description: ''},
  {header: 'After-Tax', field_name: 'after-tax', start:382, size:13, default: '', required: false, description: ''},
  {header: 'Basic', field_name: 'basic', start:395, size:13, default: '', required: false, description: ''},
  {header: 'Match', field_name: 'match', start:408, size:13, default: '', required: false, description: ''},
  {header: 'Missionary Indicator', field_name: 'missionary_indicator', start:421, size:1, default: '', required: false, description: ''},
  {header: 'Missionary Amt', field_name: 'missionary_amt', start:422, size:13, default: '', required: false, description: ''},
  {header: 'Loan Payment', field_name: 'loan_payment', start:435, size:13, default: '', required: false, description: ''},
  {header: 'Loan Number', field_name: 'loan_number', start:448, size:5, default: '', required: false, description: ''},
  {header: 'Pay Period Hours', field_name: 'pay_period_hours', start:453, size:8, default: '', required: true, description: ''},
  {header: 'Special Pay', field_name: 'special_pay', start:461, size:13, default: '', required: false, description: ''},
  {header: 'Roth 403B', field_name: 'roth_403b', start:474, size:13, default: '', required: false, description: ''},
  {header: 'ARP Gross Wages', field_name: 'arp_gross_wages', start:487, size:13, default: '', required: true, description: ''},
  {header: 'ER Guide Code', field_name: 'er_guide_code', start:500, size:1, default: '', required: true, description: ''},
  {header: 'Salary On Paper', field_name: 'salary_on_paper', start:501, size:13, default: '', required: true, description: ''},
  {header: 'Salary Period', field_name: 'salary_period', start:514, size:1, default: '', required: true, description: ''},
  {header: 'Salary Periods Expected', field_name: 'salary_periods_expected', start:515, size:4, default: '', required: true, description: ''},
  {header: 'CR LF', field_name: 'cr_lf', start:519, size:2, default: '', required: true, description: ''}
]
